import Foundation

/// Renders a Markdown meeting note for the user's vault from a cached
/// `Summary` plus the meeting's metadata. Replaces the old "second
/// Claude call that returned Markdown" path so we never re-pay the
/// input transcript cost — Claude produces the rich JSON once
/// (`generateSummary`) and this renderer composes the document.
///
/// Output skeleton matches the previous LLM-rendered shape exactly so
/// existing notes in users' vaults remain visually consistent across
/// the migration: YAML frontmatter, title + tldr blockquote, Overview /
/// Summary / Key Decisions / Action Items / Discussion Notes /
/// References / Captured Materials, then a generated-on footer.
enum MeetingNoteRenderer {

    /// Render the full Markdown note. `now` is the timestamp written
    /// into the footer — defaults to `Date()`; passed in so tests can
    /// pin it.
    static func render(
        meeting: MeetingRecord,
        summary: Summary,
        now: Date = Date()
    ) -> String {
        var out = ""
        out += renderFrontmatter(meeting: meeting)
        out += "\n# \(escapeInline(meeting.title))\n\n"
        if let tldr = summary.tldr?.trimmingCharacters(in: .whitespacesAndNewlines), !tldr.isEmpty {
            out += "> \(tldr)\n\n"
        }
        out += renderOverview(meeting: meeting)
        out += renderGoals(summary)
        out += renderSummary(summary)
        out += renderDecisions(summary)
        out += renderActionItems(summary)
        out += renderDiscussion(summary)
        out += renderReferences(meeting: meeting, summary: summary)
        out += renderCaptured(meeting: meeting)
        out += "\n---\n*Generated by Claude on \(footerTimestamp(now))*\n"
        return out
    }

    // MARK: - Sections

    private static func renderFrontmatter(meeting: MeetingRecord) -> String {
        var lines: [String] = ["---"]
        lines.append("title: \(yamlScalar(meeting.title))")
        lines.append("date: \(dateOnlyFormatter.string(from: meeting.recordedAt))")
        lines.append("time: \"\(timeFormatter.string(from: meeting.recordedAt))\"")
        if let dur = meeting.duration {
            lines.append("duration: \(formatDurationCompact(dur))")
        }
        let attendeeNames = attendeeDisplayNames(meeting: meeting)
        if attendeeNames.isEmpty {
            lines.append("attendees: []")
        } else {
            lines.append("attendees:")
            for name in attendeeNames {
                lines.append("  - \(yamlScalar(name))")
            }
        }
        if meeting.tags.isEmpty {
            lines.append("tags:")
            lines.append("  - meeting")
        } else {
            lines.append("tags:")
            lines.append("  - meeting")
            for tag in meeting.tags where tag != "meeting" {
                lines.append("  - \(yamlScalar(tag))")
            }
        }
        if let loc = meeting.calendarEvent?.location?.trimmingCharacters(in: .whitespacesAndNewlines),
           !loc.isEmpty {
            lines.append("location: \(yamlScalar(loc))")
        }
        lines.append("source: \(yamlScalar(meeting.folder.path))")
        lines.append("---\n")
        return lines.joined(separator: "\n")
    }

    private static func renderOverview(meeting: MeetingRecord) -> String {
        var lines: [String] = ["## 📋 Overview"]
        lines.append("**When:** \(formatWhen(meeting: meeting))")
        let locationText = meeting.calendarEvent?.location?
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .nilIfEmpty
        lines.append("**Where:** \(locationText ?? "_Not specified_")")
        if let url = meeting.calendarEvent?.conferenceURL {
            let host = url.host ?? url.absoluteString
            lines.append("**Conference:** [\(host)](\(url.absoluteString))")
        }
        return lines.joined(separator: "\n") + "\n\n"
    }

    /// Goals section — what the meeting was trying to achieve. Sits
    /// between Overview and Summary so the reader sees the *intent*
    /// before scanning conclusions. Skipped entirely when the LLM
    /// returned no goals (legacy summary.json, or a meeting too
    /// freeform to have a stated objective) — empty Goals header would
    /// add noise without information.
    private static func renderGoals(_ summary: Summary) -> String {
        let goals = (summary.goals ?? []).filter {
            !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        }
        guard !goals.isEmpty else { return "" }
        var lines: [String] = ["## 🎯 Goals"]
        for g in goals {
            lines.append("- \(g)")
        }
        return lines.joined(separator: "\n") + "\n\n"
    }

    private static func renderSummary(_ summary: Summary) -> String {
        let body = summary.summary.trimmingCharacters(in: .whitespacesAndNewlines)
        let content = body.isEmpty ? "_None recorded_" : body
        return "## 📝 Summary\n\(content)\n\n"
    }

    private static func renderDecisions(_ summary: Summary) -> String {
        var lines: [String] = ["## ⬆️ Decisions"]
        let decisions = (summary.keyDecisions ?? []).filter {
            !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        }
        if decisions.isEmpty {
            lines.append("_None recorded_")
        } else {
            for d in decisions {
                lines.append("- \(d)")
            }
        }
        return lines.joined(separator: "\n") + "\n\n"
    }

    private static func renderActionItems(_ summary: Summary) -> String {
        var lines: [String] = ["## ✅ Action Items"]
        if summary.actionItems.isEmpty {
            lines.append("_None_")
        } else {
            for item in summary.actionItems {
                let speaker = item.speaker.trimmingCharacters(in: .whitespacesAndNewlines)
                let text = item.text.trimmingCharacters(in: .whitespacesAndNewlines)
                let stamp = item.timestamp.trimmingCharacters(in: .whitespacesAndNewlines)
                if stamp.isEmpty {
                    lines.append("- [ ] **\(speaker)**: \(text)")
                } else {
                    lines.append("- [ ] **\(speaker)**: \(text) · `\(stamp)`")
                }
            }
        }
        return lines.joined(separator: "\n") + "\n\n"
    }

    private static func renderDiscussion(_ summary: Summary) -> String {
        var out = "## 🗣️ Discussion Notes\n"
        let topics = (summary.discussionTopics ?? []).filter { !$0.bullets.isEmpty }
        if topics.isEmpty {
            out += "_None recorded_\n"
        } else {
            for topic in topics {
                out += "### \(topic.heading.trimmingCharacters(in: .whitespacesAndNewlines))\n"
                for bullet in topic.bullets {
                    let trimmed = bullet.trimmingCharacters(in: .whitespacesAndNewlines)
                    guard !trimmed.isEmpty else { continue }
                    out += "- \(trimmed)\n"
                }
                out += "\n"
            }
        }
        if !out.hasSuffix("\n\n") { out += "\n" }
        return out
    }

    private static func renderReferences(meeting: MeetingRecord, summary: Summary) -> String {
        let refs = summary.references ?? []
        let urlItems = meeting.contextItems.filter { $0.kind == .url }
        var lines: [String] = ["## 🔗 References"]

        if !refs.isEmpty {
            // LLM-curated references are the source of truth — they
            // include URLs lifted from inside text-kind clipboard
            // bodies (chat pastes with embedded Figma / Jira links)
            // that wouldn't survive a `kind == .url` filter. For each
            // ref, attach the earliest captured timestamp by searching
            // both url-kind items (exact match) and text-kind bodies
            // (substring) so the user can still scrub to where it came
            // up in the meeting.
            let alreadyRendered = Set(refs.map(\.url))
            for ref in refs {
                let stamp = firstTimestamp(for: ref.url, in: meeting.contextItems)
                let note = ref.note?.trimmingCharacters(in: .whitespacesAndNewlines).nilIfEmpty
                let suffix = note.map { " — \($0)" } ?? ""
                let stampSuffix = stamp.map { " · `\($0)`" } ?? ""
                lines.append("- [\(escapeInline(ref.label))](\(ref.url))\(suffix)\(stampSuffix)")
            }
            // Any url-kind items the LLM didn't pull into references
            // (e.g. it deemed them noise) still get a bare bullet so
            // the user sees nothing was silently dropped.
            for item in urlItems {
                let urlString = (item.text ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
                guard !urlString.isEmpty, !alreadyRendered.contains(urlString) else { continue }
                let stamp = formatTimestamp(item.offset)
                let label = item.pageTitle?.trimmingCharacters(in: .whitespacesAndNewlines).nilIfEmpty
                    ?? urlString
                lines.append("- [\(escapeInline(label))](\(urlString)) · `\(stamp)`")
            }
        } else if urlItems.isEmpty {
            lines.append("_None_")
        } else {
            for item in urlItems {
                let urlString = (item.text ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
                guard !urlString.isEmpty else { continue }
                let stamp = formatTimestamp(item.offset)
                let label = item.pageTitle?.trimmingCharacters(in: .whitespacesAndNewlines).nilIfEmpty
                    ?? urlString
                lines.append("- [\(escapeInline(label))](\(urlString)) · `\(stamp)`")
            }
        }
        return lines.joined(separator: "\n") + "\n\n"
    }

    /// Earliest captured offset where `url` shows up — either as the
    /// entire payload of a `.url` item, or embedded in the body of a
    /// `.text` item. Returns nil if the URL doesn't appear in the
    /// meeting's context items (shouldn't happen with the current
    /// prompt rules, but the LLM is free to invent a reference and we
    /// won't make up a timestamp for one).
    private static func firstTimestamp(for url: String, in items: [ContextItem]) -> String? {
        let needle = url.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !needle.isEmpty else { return nil }
        let match = items
            .filter { item in
                switch item.kind {
                case .url:
                    return (item.text ?? "").trimmingCharacters(in: .whitespacesAndNewlines) == needle
                case .text:
                    return (item.text ?? "").contains(needle)
                case .image:
                    return false
                }
            }
            .min(by: { $0.offset < $1.offset })
        return match.map { formatTimestamp($0.offset) }
    }

    private static func renderCaptured(meeting: MeetingRecord) -> String {
        let imageItems = meeting.contextItems.filter { $0.kind == .image }
        // Text items that aren't already covered by References. A text
        // item whose entire payload is a single URL is now reclassified
        // as kind=.url at capture time, but legacy meetings recorded
        // before that fix kept them as .text — drop those here so they
        // don't duplicate the References bullet.
        let textItems = meeting.contextItems.filter { item in
            guard item.kind == .text else { return false }
            let trimmed = (item.text ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
            return !Self.isStandaloneURL(trimmed)
        }
        var lines: [String] = ["## 📎 Captured Materials"]
        if imageItems.isEmpty && textItems.isEmpty {
            lines.append("_None_")
        } else {
            for item in imageItems {
                let stamp = formatTimestamp(item.offset)
                if let filename = item.imageFilename, !filename.isEmpty {
                    lines.append("- 📎 `clipboard/\(filename)` · `\(stamp)`")
                } else {
                    lines.append("- 📎 _image_ · `\(stamp)`")
                }
            }
            for item in textItems {
                let stamp = formatTimestamp(item.offset)
                let body = item.text ?? ""
                if Self.looksLikeMermaid(body) {
                    // Drop the source into a ```mermaid fence so Obsidian's
                    // Mermaid renderer turns it into the diagram inline.
                    // Far more useful than 30 lines of `sequenceDiagram`
                    // text the reader has to mentally compile.
                    lines.append("- 🧜 Mermaid diagram · `\(stamp)`")
                    lines.append("```mermaid")
                    lines.append(body.trimmingCharacters(in: .whitespacesAndNewlines))
                    lines.append("```")
                } else {
                    // Anything else: a short quoted preview. Truncate at
                    // 400 chars so a chat paste or a giant code dump
                    // doesn't bloat the note — the reader can open the
                    // meeting folder if they want the full content.
                    lines.append("- 📋 Clipboard text · `\(stamp)`")
                    let preview: String = {
                        let collapsed = body.trimmingCharacters(in: .whitespacesAndNewlines)
                        guard collapsed.count > 400 else { return collapsed }
                        return String(collapsed.prefix(400)) + "…"
                    }()
                    for line in preview.split(separator: "\n", omittingEmptySubsequences: false) {
                        lines.append("  > \(line)")
                    }
                }
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// True when the trimmed text is exactly one well-formed http(s) URL
    /// with a host — mirrors ClipboardWatcher.isStandaloneURL so the
    /// "skip already-in-References URLs" filter matches what would have
    /// been promoted to .url at capture time on the new build.
    private static func isStandaloneURL(_ s: String) -> Bool {
        guard !s.isEmpty,
              !s.contains(where: { $0.isWhitespace || $0.isNewline }) else { return false }
        let lower = s.lowercased()
        guard lower.hasPrefix("http://") || lower.hasPrefix("https://") else { return false }
        guard let url = URL(string: s), let host = url.host, !host.isEmpty else { return false }
        return true
    }

    /// Detect Mermaid source by its leading directive. Covers the
    /// diagram types most likely to show up in a meeting: sequence,
    /// flowchart/graph, class, state, ER, gantt, pie, journey, gitgraph.
    /// Case-insensitive because Mermaid accepts mixed case, but the
    /// directive must be the first token after any leading whitespace.
    private static func looksLikeMermaid(_ s: String) -> Bool {
        let head = s.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        let prefixes = [
            "sequencediagram", "graph ", "graph\t", "flowchart ", "flowchart\t",
            "classdiagram", "statediagram", "erdiagram", "gantt", "pie ", "pie\n",
            "journey", "gitgraph", "mindmap", "timeline"
        ]
        return prefixes.contains { head.hasPrefix($0) }
    }

    // MARK: - Field helpers

    /// Attendee names for the YAML frontmatter. Prefer the meeting's
    /// speaker profiles when present (those reflect the user's actual
    /// rename / mapping), falling back to calendar attendees on
    /// meetings that never got a speaker mapping. Skips "Me"-style
    /// labels — the user's own name typically already appears via the
    /// calendar attendee list as `isMe`.
    private static func attendeeDisplayNames(meeting: MeetingRecord) -> [String] {
        if !meeting.speakerProfiles.isEmpty {
            return meeting.speakerProfiles
                .map { $0.displayName.trimmingCharacters(in: .whitespacesAndNewlines) }
                .filter { !$0.isEmpty }
        }
        if let event = meeting.calendarEvent {
            var names: [String] = []
            if let organizer = event.organizer {
                names.append(organizer.displayName)
            }
            for a in event.attendees where !a.isMe {
                names.append(a.displayName)
            }
            return names.map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
                .filter { !$0.isEmpty }
        }
        return []
    }

    private static func formatWhen(meeting: MeetingRecord) -> String {
        let start = meeting.recordedAt
        let end = meeting.duration.map { start.addingTimeInterval($0) }
        let datePart = dateOnlyFormatter.string(from: start)
        let startTime = timeFormatter.string(from: start)
        if let end {
            let endTime = timeFormatter.string(from: end)
            let dur = formatDurationCompact(meeting.duration ?? 0)
            return "\(datePart) \(startTime) — \(endTime) (\(dur))"
        }
        return "\(datePart) \(startTime)"
    }

    private static func formatDurationCompact(_ d: TimeInterval) -> String {
        let total = Int(d.rounded())
        let h = total / 3600
        let m = (total / 60) % 60
        let s = total % 60
        if h > 0 { return "\(h)h \(m)m" }
        if m > 0 { return "\(m)m" }
        return "\(s)s"
    }

    private static func formatTimestamp(_ t: TimeInterval) -> String {
        let total = max(0, Int(t))
        let h = total / 3600
        let m = (total / 60) % 60
        let s = total % 60
        return h > 0
            ? String(format: "%d:%02d:%02d", h, m, s)
            : String(format: "%02d:%02d", m, s)
    }

    private static func footerTimestamp(_ d: Date) -> String {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "yyyy-MM-dd HH:mm"
        return f.string(from: d)
    }

    /// Quote a string for YAML frontmatter when it contains characters
    /// that would otherwise need escaping (`:`, `#`, leading/trailing
    /// whitespace, quotes). Plain values pass through unquoted.
    private static func yamlScalar(_ s: String) -> String {
        let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty { return "\"\"" }
        let needsQuoting = trimmed.contains(":")
            || trimmed.contains("#")
            || trimmed.contains("\"")
            || trimmed.contains("\n")
            || trimmed != s
            || ["true", "false", "yes", "no", "null"].contains(trimmed.lowercased())
        if !needsQuoting { return trimmed }
        let escaped = trimmed
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }

    /// Escape characters that would break inline Markdown contexts
    /// (link labels, headings). Conservative — only escapes brackets
    /// and backticks since those are what cause real rendering issues
    /// in the slots we use this for.
    private static func escapeInline(_ s: String) -> String {
        s.replacingOccurrences(of: "[", with: "\\[")
         .replacingOccurrences(of: "]", with: "\\]")
    }

    private static let dateOnlyFormatter: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "yyyy-MM-dd"
        return f
    }()

    private static let timeFormatter: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "HH:mm"
        return f
    }()
}

private extension String {
    var nilIfEmpty: String? { isEmpty ? nil : self }
}
