import Foundation

/// Renders a Markdown meeting note for the user's vault from a cached
/// `Summary` plus the meeting's metadata. Replaces the old "second
/// Claude call that returned Markdown" path so we never re-pay the
/// input transcript cost — Claude produces the rich JSON once
/// (`generateSummary`) and this renderer composes the document.
///
/// Output skeleton matches the previous LLM-rendered shape exactly so
/// existing notes in users' vaults remain visually consistent across
/// the migration: YAML frontmatter, title + tldr blockquote, Overview /
/// Summary / Key Decisions / Action Items / Discussion Notes /
/// References / Captured Materials, then a generated-on footer.
enum MeetingNoteRenderer {

    /// Render the full Markdown note. `now` is the timestamp written
    /// into the footer — defaults to `Date()`; passed in so tests can
    /// pin it.
    static func render(
        meeting: MeetingRecord,
        summary: Summary,
        now: Date = Date()
    ) -> String {
        var out = ""
        out += renderFrontmatter(meeting: meeting)
        out += "\n# \(escapeInline(meeting.title))\n\n"
        if let tldr = summary.tldr?.trimmingCharacters(in: .whitespacesAndNewlines), !tldr.isEmpty {
            out += "> \(tldr)\n\n"
        }
        out += renderOverview(meeting: meeting)
        out += renderSummary(summary)
        out += renderDecisions(summary)
        out += renderActionItems(summary)
        out += renderDiscussion(summary)
        out += renderReferences(meeting: meeting)
        out += renderCaptured(meeting: meeting)
        out += "\n---\n*Generated by Claude on \(footerTimestamp(now))*\n"
        return out
    }

    // MARK: - Sections

    private static func renderFrontmatter(meeting: MeetingRecord) -> String {
        var lines: [String] = ["---"]
        lines.append("title: \(yamlScalar(meeting.title))")
        lines.append("date: \(dateOnlyFormatter.string(from: meeting.recordedAt))")
        lines.append("time: \"\(timeFormatter.string(from: meeting.recordedAt))\"")
        if let dur = meeting.duration {
            lines.append("duration: \(formatDurationCompact(dur))")
        }
        let attendeeNames = attendeeDisplayNames(meeting: meeting)
        if attendeeNames.isEmpty {
            lines.append("attendees: []")
        } else {
            lines.append("attendees:")
            for name in attendeeNames {
                lines.append("  - \(yamlScalar(name))")
            }
        }
        if meeting.tags.isEmpty {
            lines.append("tags:")
            lines.append("  - meeting")
        } else {
            lines.append("tags:")
            lines.append("  - meeting")
            for tag in meeting.tags where tag != "meeting" {
                lines.append("  - \(yamlScalar(tag))")
            }
        }
        if let loc = meeting.calendarEvent?.location?.trimmingCharacters(in: .whitespacesAndNewlines),
           !loc.isEmpty {
            lines.append("location: \(yamlScalar(loc))")
        }
        lines.append("source: \(yamlScalar(meeting.folder.path))")
        lines.append("---\n")
        return lines.joined(separator: "\n")
    }

    private static func renderOverview(meeting: MeetingRecord) -> String {
        var lines: [String] = ["## Overview"]
        lines.append("**When:** \(formatWhen(meeting: meeting))")
        let locationText = meeting.calendarEvent?.location?
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .nilIfEmpty
        lines.append("**Where:** \(locationText ?? "_Not specified_")")
        if let url = meeting.calendarEvent?.conferenceURL {
            let host = url.host ?? url.absoluteString
            lines.append("**Conference:** [\(host)](\(url.absoluteString))")
        }
        return lines.joined(separator: "\n") + "\n\n"
    }

    private static func renderSummary(_ summary: Summary) -> String {
        let body = summary.summary.trimmingCharacters(in: .whitespacesAndNewlines)
        let content = body.isEmpty ? "_None recorded_" : body
        return "## Summary\n\(content)\n\n"
    }

    private static func renderDecisions(_ summary: Summary) -> String {
        var lines: [String] = ["## Key Decisions"]
        let decisions = (summary.keyDecisions ?? []).filter {
            !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        }
        if decisions.isEmpty {
            lines.append("_None recorded_")
        } else {
            for d in decisions {
                lines.append("- \(d)")
            }
        }
        return lines.joined(separator: "\n") + "\n\n"
    }

    private static func renderActionItems(_ summary: Summary) -> String {
        var lines: [String] = ["## Action Items"]
        if summary.actionItems.isEmpty {
            lines.append("_None_")
        } else {
            for item in summary.actionItems {
                let speaker = item.speaker.trimmingCharacters(in: .whitespacesAndNewlines)
                let text = item.text.trimmingCharacters(in: .whitespacesAndNewlines)
                let stamp = item.timestamp.trimmingCharacters(in: .whitespacesAndNewlines)
                if stamp.isEmpty {
                    lines.append("- [ ] **\(speaker)**: \(text)")
                } else {
                    lines.append("- [ ] **\(speaker)**: \(text) · `\(stamp)`")
                }
            }
        }
        return lines.joined(separator: "\n") + "\n\n"
    }

    private static func renderDiscussion(_ summary: Summary) -> String {
        var out = "## Discussion Notes\n"
        let topics = (summary.discussionTopics ?? []).filter { !$0.bullets.isEmpty }
        if topics.isEmpty {
            out += "_None recorded_\n"
        } else {
            for topic in topics {
                out += "### \(topic.heading.trimmingCharacters(in: .whitespacesAndNewlines))\n"
                for bullet in topic.bullets {
                    let trimmed = bullet.trimmingCharacters(in: .whitespacesAndNewlines)
                    guard !trimmed.isEmpty else { continue }
                    out += "- \(trimmed)\n"
                }
                out += "\n"
            }
        }
        if !out.hasSuffix("\n\n") { out += "\n" }
        return out
    }

    private static func renderReferences(meeting: MeetingRecord) -> String {
        let urlItems = meeting.contextItems.filter { $0.kind == .url }
        var lines: [String] = ["## References"]
        if urlItems.isEmpty {
            lines.append("_None_")
        } else {
            for item in urlItems {
                let urlString = (item.text ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
                guard !urlString.isEmpty else { continue }
                let label = item.pageTitle?.trimmingCharacters(in: .whitespacesAndNewlines).nilIfEmpty
                    ?? urlString
                let stamp = formatTimestamp(item.offset)
                lines.append("- [\(escapeInline(label))](\(urlString)) · `\(stamp)`")
            }
        }
        return lines.joined(separator: "\n") + "\n\n"
    }

    private static func renderCaptured(meeting: MeetingRecord) -> String {
        let imageItems = meeting.contextItems.filter { $0.kind == .image }
        var lines: [String] = ["## Captured Materials"]
        if imageItems.isEmpty {
            lines.append("_None_")
        } else {
            for item in imageItems {
                let stamp = formatTimestamp(item.offset)
                if let filename = item.imageFilename, !filename.isEmpty {
                    lines.append("- 📎 `clipboard/\(filename)` · `\(stamp)`")
                } else {
                    lines.append("- 📎 _image_ · `\(stamp)`")
                }
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Field helpers

    /// Attendee names for the YAML frontmatter. Prefer the meeting's
    /// speaker profiles when present (those reflect the user's actual
    /// rename / mapping), falling back to calendar attendees on
    /// meetings that never got a speaker mapping. Skips "Me"-style
    /// labels — the user's own name typically already appears via the
    /// calendar attendee list as `isMe`.
    private static func attendeeDisplayNames(meeting: MeetingRecord) -> [String] {
        if !meeting.speakerProfiles.isEmpty {
            return meeting.speakerProfiles
                .map { $0.displayName.trimmingCharacters(in: .whitespacesAndNewlines) }
                .filter { !$0.isEmpty }
        }
        if let event = meeting.calendarEvent {
            var names: [String] = []
            if let organizer = event.organizer {
                names.append(organizer.displayName)
            }
            for a in event.attendees where !a.isMe {
                names.append(a.displayName)
            }
            return names.map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
                .filter { !$0.isEmpty }
        }
        return []
    }

    private static func formatWhen(meeting: MeetingRecord) -> String {
        let start = meeting.recordedAt
        let end = meeting.duration.map { start.addingTimeInterval($0) }
        let datePart = dateOnlyFormatter.string(from: start)
        let startTime = timeFormatter.string(from: start)
        if let end {
            let endTime = timeFormatter.string(from: end)
            let dur = formatDurationCompact(meeting.duration ?? 0)
            return "\(datePart) \(startTime) — \(endTime) (\(dur))"
        }
        return "\(datePart) \(startTime)"
    }

    private static func formatDurationCompact(_ d: TimeInterval) -> String {
        let total = Int(d.rounded())
        let h = total / 3600
        let m = (total / 60) % 60
        let s = total % 60
        if h > 0 { return "\(h)h \(m)m" }
        if m > 0 { return "\(m)m" }
        return "\(s)s"
    }

    private static func formatTimestamp(_ t: TimeInterval) -> String {
        let total = max(0, Int(t))
        let h = total / 3600
        let m = (total / 60) % 60
        let s = total % 60
        return h > 0
            ? String(format: "%d:%02d:%02d", h, m, s)
            : String(format: "%02d:%02d", m, s)
    }

    private static func footerTimestamp(_ d: Date) -> String {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "yyyy-MM-dd HH:mm"
        return f.string(from: d)
    }

    /// Quote a string for YAML frontmatter when it contains characters
    /// that would otherwise need escaping (`:`, `#`, leading/trailing
    /// whitespace, quotes). Plain values pass through unquoted.
    private static func yamlScalar(_ s: String) -> String {
        let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty { return "\"\"" }
        let needsQuoting = trimmed.contains(":")
            || trimmed.contains("#")
            || trimmed.contains("\"")
            || trimmed.contains("\n")
            || trimmed != s
            || ["true", "false", "yes", "no", "null"].contains(trimmed.lowercased())
        if !needsQuoting { return trimmed }
        let escaped = trimmed
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }

    /// Escape characters that would break inline Markdown contexts
    /// (link labels, headings). Conservative — only escapes brackets
    /// and backticks since those are what cause real rendering issues
    /// in the slots we use this for.
    private static func escapeInline(_ s: String) -> String {
        s.replacingOccurrences(of: "[", with: "\\[")
         .replacingOccurrences(of: "]", with: "\\]")
    }

    private static let dateOnlyFormatter: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "yyyy-MM-dd"
        return f
    }()

    private static let timeFormatter: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "HH:mm"
        return f
    }()
}

private extension String {
    var nilIfEmpty: String? { isEmpty ? nil : self }
}
