import XCTest
@testable import Meeting

final class MeetingNoteRendererTests: XCTestCase {

    // MARK: - Skeleton parity

    func test_render_includesAllSections() {
        let markdown = MeetingNoteRenderer.render(
            meeting: makeMeeting(),
            summary: makeRichSummary(),
            now: Self.fixedNow
        )
        // Frontmatter + body skeleton matches the old LLM-rendered shape.
        XCTAssertTrue(markdown.hasPrefix("---\n"), "must open with YAML frontmatter")
        XCTAssertTrue(markdown.contains("title: Q1 Planning"))
        XCTAssertTrue(markdown.contains("date: 2026-04-29"))
        XCTAssertTrue(markdown.contains("time: \"14:30\""))
        XCTAssertTrue(markdown.contains("duration: 1h 0m"))
        XCTAssertTrue(markdown.contains("attendees:"))
        XCTAssertTrue(markdown.contains("- Me"))
        XCTAssertTrue(markdown.contains("- Pim"))
        XCTAssertTrue(markdown.contains("source: /tmp/meeting"))

        XCTAssertTrue(markdown.contains("\n# Q1 Planning\n"))
        XCTAssertTrue(markdown.contains("\n> Decided to ship feature X by Mar 15.\n"))
        XCTAssertTrue(markdown.contains("\n## Overview\n"))
        XCTAssertTrue(markdown.contains("**When:** 2026-04-29 14:30 — 15:30 (1h 0m)"))
        XCTAssertTrue(markdown.contains("**Where:** Zoom"))
        XCTAssertTrue(markdown.contains("\n## Summary\n"))
        XCTAssertTrue(markdown.contains("**ship feature X**"))
        XCTAssertTrue(markdown.contains("\n## Key Decisions\n"))
        XCTAssertTrue(markdown.contains("- Move Q1 release to Mar 15"))
        XCTAssertTrue(markdown.contains("\n## Action Items\n"))
        XCTAssertTrue(markdown.contains("- [ ] **Pim**: Move Aof to agent track · `14:22`"))
        XCTAssertTrue(markdown.contains("\n## Discussion Notes\n"))
        XCTAssertTrue(markdown.contains("\n### Q1 Roadmap\n"))
        XCTAssertTrue(markdown.contains("- Customer X needs feature by Mar 15"))
        XCTAssertTrue(markdown.contains("\n## References\n"))
        XCTAssertTrue(markdown.contains("- [Spec doc](https://example.com/spec) · `05:12`"))
        XCTAssertTrue(markdown.contains("\n## Captured Materials\n"))
        XCTAssertTrue(markdown.contains("- 📎 `clipboard/screenshot.png` · `12:00`"))
        XCTAssertTrue(markdown.contains("*Generated by Claude on 2026-04-29 16:00*"))
    }

    // MARK: - Empty-section fallbacks

    func test_render_emptySectionsShowPlaceholder() {
        let markdown = MeetingNoteRenderer.render(
            meeting: makeMeeting(contextItems: []),
            summary: Summary(
                summary: "",
                actionItems: [],
                generatedAt: Self.fixedNow,
                providerName: "Claude CLI",
                tldr: nil,
                keyDecisions: [],
                discussionTopics: []
            ),
            now: Self.fixedNow
        )
        XCTAssertTrue(markdown.contains("## Summary\n_None recorded_"))
        XCTAssertTrue(markdown.contains("## Key Decisions\n_None recorded_"))
        XCTAssertTrue(markdown.contains("## Action Items\n_None_"))
        XCTAssertTrue(markdown.contains("## Discussion Notes\n_None recorded_"))
        XCTAssertTrue(markdown.contains("## References\n_None_"))
        XCTAssertTrue(markdown.contains("## Captured Materials\n_None_"))
    }

    // MARK: - Frontmatter quoting

    func test_render_quotesYamlSpecials() {
        let meeting = makeMeeting(title: "1:1 with Pim: planning")
        let markdown = MeetingNoteRenderer.render(
            meeting: meeting,
            summary: makeRichSummary(),
            now: Self.fixedNow
        )
        // Title contains a colon — must be quoted in frontmatter.
        XCTAssertTrue(markdown.contains("title: \"1:1 with Pim: planning\""))
        // Heading uses the raw title (no escaping needed for colons in
        // body text).
        XCTAssertTrue(markdown.contains("\n# 1:1 with Pim: planning\n"))
    }

    // MARK: - tldr handling

    func test_render_skipsTldrBlockquoteWhenAbsent() {
        var summary = makeRichSummary()
        summary.tldr = nil
        let markdown = MeetingNoteRenderer.render(
            meeting: makeMeeting(),
            summary: summary,
            now: Self.fixedNow
        )
        XCTAssertFalse(markdown.contains("\n> "), "no blockquote when tldr is nil")
        // Should jump straight from title to Overview.
        XCTAssertTrue(markdown.contains("\n# Q1 Planning\n\n## Overview\n"))
    }

    // MARK: - Fixtures

    private static let fixedNow: Date = {
        var components = DateComponents()
        components.year = 2026
        components.month = 4
        components.day = 29
        components.hour = 16
        components.minute = 0
        components.timeZone = TimeZone(identifier: "Asia/Bangkok")
        return Calendar(identifier: .gregorian).date(from: components)!
    }()

    private static let recordedAt: Date = {
        var components = DateComponents()
        components.year = 2026
        components.month = 4
        components.day = 29
        components.hour = 14
        components.minute = 30
        components.timeZone = TimeZone(identifier: "Asia/Bangkok")
        return Calendar(identifier: .gregorian).date(from: components)!
    }()

    private func makeMeeting(
        title: String = "Q1 Planning",
        contextItems: [ContextItem]? = nil
    ) -> MeetingRecord {
        let items = contextItems ?? [
            ContextItem(
                id: UUID(),
                kind: .url,
                source: .browser,
                capturedAt: Self.recordedAt.addingTimeInterval(312),
                offset: 312,
                text: "https://example.com/spec",
                imageFilename: nil,
                browserName: "Safari",
                pageTitle: "Spec doc"
            ),
            ContextItem(
                id: UUID(),
                kind: .image,
                source: .clipboard,
                capturedAt: Self.recordedAt.addingTimeInterval(720),
                offset: 720,
                text: nil,
                imageFilename: "screenshot.png",
                browserName: nil,
                pageTitle: nil
            ),
        ]
        return MeetingRecord(
            folder: URL(fileURLWithPath: "/tmp/meeting"),
            recordedAt: Self.recordedAt,
            title: title,
            originalTitle: nil,
            duration: 3600,
            speakerCount: 2,
            speakers: [
                Speaker(id: .me, displayName: "Me"),
                Speaker(id: SpeakerID(rawValue: "speaker_0"), displayName: "Pim"),
            ],
            speakerProfiles: [
                SpeakerProfile(id: .me, displayName: "Me"),
                SpeakerProfile(
                    id: SpeakerID(rawValue: "speaker_0"),
                    displayName: "Pim",
                    email: "pim@example.com",
                    role: "chair"
                ),
            ],
            appName: "Zoom",
            tags: [],
            starred: false,
            hasTranscript: true,
            summary: nil,
            calendarEvent: CalendarEvent(
                eventIdentifier: "evt-1",
                externalIdentifier: nil,
                title: "Q1 Planning",
                startDate: Self.recordedAt,
                endDate: Self.recordedAt.addingTimeInterval(3600),
                location: "Zoom",
                conferenceURL: URL(string: "https://zoom.us/j/123"),
                calendarName: "Work",
                organizer: nil,
                attendees: [],
                openInCalendarURL: nil
            ),
            meetParticipants: [],
            contextItems: items
        )
    }

    private func makeRichSummary() -> Summary {
        Summary(
            summary: "We agreed to **ship feature X** by Mar 15. Engineering capacity remains tight.",
            actionItems: [
                ActionItem(speaker: "Pim", text: "Move Aof to agent track", timestamp: "14:22")
            ],
            generatedAt: Self.fixedNow,
            providerName: "Claude CLI",
            tldr: "Decided to ship feature X by Mar 15.",
            keyDecisions: ["Move Q1 release to Mar 15"],
            discussionTopics: [
                DiscussionTopic(
                    heading: "Q1 Roadmap",
                    bullets: [
                        "Customer X needs feature by Mar 15",
                        "Engineering capacity tight after Tar's leave",
                    ]
                )
            ]
        )
    }
}
